# Generated by Django 2.2.8 on 2020-09-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='LABEL',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
