# Generated by Django 2.2.8 on 2020-09-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0002_auto_20200908_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
    ]
