# Generated by Django 2.2.8 on 2020-09-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description gkkjsdnbdnb jbhljkcgfudkg'),
            preserve_default=False,
        ),
    ]
