# Generated by Django 2.2.8 on 2020-09-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0005_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
